// <auto-generated />
using System;
using BowsFormulaOneAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BowsFormulaOne.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("BowsFormulaOneAPI.Data.Models.PhoneNumberDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserDtoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserDtoId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 10, 5, 10, 45, 24, 625, DateTimeKind.Local).AddTicks(2420),
                            PhoneNumber = "07767987200",
                            UserDtoId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 10, 5, 10, 45, 24, 625, DateTimeKind.Local).AddTicks(2996),
                            PhoneNumber = "07767986200",
                            UserDtoId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 10, 5, 10, 45, 24, 625, DateTimeKind.Local).AddTicks(3005),
                            PhoneNumber = "07767987206",
                            UserDtoId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 10, 5, 10, 45, 24, 625, DateTimeKind.Local).AddTicks(3008),
                            PhoneNumber = "07767987201",
                            UserDtoId = 2
                        });
                });

            modelBuilder.Entity("BowsFormulaOneAPI.Data.Models.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 5, 10, 45, 24, 622, DateTimeKind.Local).AddTicks(7558),
                            EmployeeNumber = "r7jTG7dqBy5wGO4L",
                            FirstName = "Maxwell",
                            IsDeleted = false,
                            LastName = "Archer",
                            ModifiedDate = new DateTime(2021, 10, 5, 10, 45, 24, 624, DateTimeKind.Local).AddTicks(4027)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 5, 10, 45, 24, 624, DateTimeKind.Local).AddTicks(4970),
                            EmployeeNumber = "r7jTG8dqBy5wGO4L",
                            FirstName = "Alexandra",
                            IsDeleted = false,
                            LastName = "Archer",
                            ModifiedDate = new DateTime(2021, 10, 5, 10, 45, 24, 624, DateTimeKind.Local).AddTicks(4980)
                        });
                });

            modelBuilder.Entity("BowsFormulaOneAPI.Data.Models.PhoneNumberDto", b =>
                {
                    b.HasOne("BowsFormulaOneAPI.Data.Models.UserDto", null)
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BowsFormulaOneAPI.Data.Models.UserDto", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
